In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../outputs/table.csv")
df.sample(5)

,phoneme_id,speaker_id,sentence_id,repetition,phoneme,onset_s,offset_s,duration_ms,l1_status,gender,wav_path,tg_path
2273,AG_sérieux_rep2_p8_ʁ,AG,sérieux,2,ʁ,1.83000,1.92000,90.00,L1,m,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
18090,UV_louche_rep6_p4_ʃ,UV,louche,6,ʃ,1.52204,1.63000,107.96,L2,f,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
6993,DD_pour gabriel_rep6_p10_ɛ,DD,pour gabriel,6,ɛ,1.66168,1.76000,98.32,L2,f,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
4983,AR_j'en chie_rep6_p0_i,AR,j'en chie,6,i,0.47000,0.59031,120.31,L1,m,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
16894,UR_tulle_rep5_p5_t,UR,tulle,5,t,1.62277,1.66000,37.23,L2,f,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...

In [3]:
df_feature = pd.read_csv("../outputs/features_acoustic.csv")
df_feature.sample(5)

,phoneme_id,phoneme,speaker_id,sentence_id,repetition,duration_ms,l1_status,gender,F1_mid,F2_mid,F3_mid,f0_mid,SCG,F1_25,F2_25,F1_75,F2_75
10226,MD_tsarine_rep1_p0_d,d,MD,tsarine,1,100.00,L1,m,310.148833,1403.120545,NaN,NaN,NaN,251.125202,1566.180088,351.537535,1697.392501
13557,SD_tulle_rep3_p8_ɑ,ɑ,SD,tulle,3,60.00,L1,f,541.919484,891.697289,2736.303885,NaN,NaN,NaN,NaN,NaN,NaN
16074,SV_divan_rep6_p4_v,v,SV,divan,6,84.03,L1,m,298.595164,1639.421082,NaN,NaN,349.797571,NaN,NaN,NaN,NaN
18239,UV_pas ceux_rep6_p7_ʁ,ʁ,UV,pas ceux,6,60.00,L2,f,437.171412,1224.984675,NaN,NaN,368.986305,NaN,NaN,NaN,NaN
9807,KV_garage_rep4_p1_i,i,KV,garage,4,157.63,L2,m,347.633848,2447.192596,3004.085638,NaN,NaN,317.326370,2320.847913,357.583289,2529.853730

In [ ]:
print(str(df["phoneme"].unique()))
v = ["u:","œ̃", "ɨ", "œ", "y̥", "ø̰", "ɪ", "ə̰", "æ", "aː", "ə", "ʉ", "a̰", "ɛ̰", "ɑ̰̃", "ɛ̃", "i̥", "ɑ̃ː", "ɛ", "u", "y", "o", "e", "ɑ", "ø", "a", "ɑ̃", "i"]
f = ["ʒ", "ʃ", "ʁ", "f", "s", "z", "v", "ʀ", "ʁ̥", "ʒ̥", "sː", "ʐ", "ɕ", "ʀ̥", "ɬ", "ɫ", "ʁ̞", "ʒʲ", "ʂ", "ç", "v̥", "h", "x", "sʲ", "ʒ̞", "ʃː"]

high = ["u:", "ɨ", "y̥", "ɪ", "ʉ","i̥", "u", "y", "i"]
mid = ["œ̃","œ","ø̰","ə̰","ə","ɛ̰","ɛ̃","ɛ","o", "e","ø"]
low = ["æ", "aː", "a̰", "ɑ̰̃", "ɑ̃ː", "ɑ", "a", "ɑ̃"]


nasal = ["œ̃","ɑ̰̃", "ɛ̃","ɑ̃ː","ɑ̃"]
oral = ["u:","ɨ", "œ", "y̥", "ø̰", "ɪ", "ə̰", "æ", "aː", "ə", "ʉ", "a̰", "ɛ̰", "i̥","ɛ", "u", "y", "o", "e", "ɑ", "ø", "a","i"]

front = ["œ̃","œ", "y̥", "ø̰", "ɪ","æ", "aː","a̰", "ɛ̰","ɛ̃", "i̥", "ɛ","y","e","ø", "a","i"]
central = ["ɨ", "ə̰", "ə", "ʉ"]
back = ["u:", "ɑ̰̃", "ɑ̃ː", "u", "o", "ɑ", "ɑ̃"]

<StringArray>
[  'd',   'i',   'ʒ',  'ɑ̃',   'ʃ',   't',   'ʁ',   'w',   'a',   'f',   'j',
   'y',   'k',   's',   'p',   'o',   'z',   'e',   'ɑ',   'ø',   'ɡ', 't͡s',
   'n',   'l',   'u',   'v',   'ɛ',   'ʀ',   'b',  'ʁ̥',   'ŋ', 'ɑ̃ː',  'b̥',
   'ə',  'ʒ̥',   'ʉ',  'ɡ̥',  'sː',  'l̝',  'a̰',  'ɛ̰', 'ɑ̰̃',  'ɛ̃',  'i̥',
   'ʐ',   'ɕ',  'ʀ̥',  'aː',  'tʲ',   'æ',  'l̰',   'ɬ',  'lʲ',  'ə̰',   'ɪ',
  'l̥',  'y̥',   'ɫ',  'ʁ̞',  'ʒʲ',  'd̥',  'pʰ',  'ø̰',   'ʂ',  'ç',  'n̰',
  'v̥',   'h',   'x',  'sʲ',   'ʝ',  'ʒ̞',  'j̥', 'd͡ʒ',  'œ̃',   'ɨ',   'œ',
  'u:',  'ʃː']
Length: 79, dtype: str

In [ ]:
import parselmouth
from parselmouth.praat import call
import numpy as np
from pathlib import Path

data_dir = Path("/home/onyxia/work/data/ru-fr_interference/2/wav_et_textgrids")
wav = next(data_dir.rglob("*.wav"))
print(wav)
sound = parselmouth.Sound(str(wav))
segment = sound.extract_part(from_time=0.1, to_time=0.3, preserve_times=True)
pitch = call(segment, "To Pitch (ac)",
             0.0,    # time step (0 = auto)
             75.0,   # pitch floor (Hz)
             15,     # max number of candidates
             "yes",  # very accurate
             0.03,   # silence threshold
             0.45,   # voicing threshold
             0.01,   # octave cost
             0.35,   # octave-jump cost
             0.14,   # voiced/unvoiced cost
             600.0)  # pitch ceiling (Hz)
val = call(pitch, "Get value at time", 0.2, "Hertz", "Linear")
print(val)

/home/onyxia/work/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/SD/sd_fra_list1_FRcorp30.wav

PraatError: Command requires more than the given 9 arguments: no value for argument "Pitch ceiling".