In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("../outputs/table.csv")
df.sample(5)

,phoneme_id,speaker_id,sentence_id,repetition,phoneme,onset_s,offset_s,duration_ms,l1_status,gender,wav_path,tg_path
13810,SD_tulle_rep5_p3_l,SD,tulle,5,l,1.06759,1.16557,97.98,L1,f,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
3767,AN_pas ceux_rep5_p10_f,AN,pas ceux,5,f,1.23000,1.36000,130.00,L1,m,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
468,AB_cache cache_rep4_p4_ʃ,AB,cache cache,4,ʃ,0.96000,1.11190,151.90,L2,f,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
9284,KV_j'en chie_rep2_p11_w,KV,j'en chie,2,w,2.39000,2.47000,80.00,L2,m,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
16363,UR_tulle_rep2_p5_t,UR,tulle,2,t,2.03000,2.09000,60.00,L2,f,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...

In [5]:
df_feature = pd.read_csv("../outputs/features_acoustic.csv")
df_feature.sample(5)

,phoneme_id,F1_mid,F2_mid,F3_mid,f0_mid,SCG,F1_25,F2_25,F1_75,F2_75
19049,YC_pour gabriel_rep1_p7_b,360.117358,1353.639166,2549.968903,192.379133,272.665897,NaN,NaN,NaN,NaN
12094,MM_pour gabriel_rep6_p2_p,1238.573278,2191.621158,3498.924978,NaN,941.759429,1192.087285,2212.213067,1193.303320,1981.184198
16503,UR_cache cache_rep3_p9_ʁ,731.059704,1562.184136,3096.904729,NaN,1350.138628,NaN,NaN,NaN,NaN
15916,SV_pas ceux_rep5_p10_f,642.310530,1841.614917,2485.906378,NaN,1998.679110,908.971965,1366.946762,697.544778,1191.197832
18100,UV_garage_rep5_p2_ɡ,243.398903,2117.310463,3221.775262,203.742524,352.508587,NaN,NaN,NaN,NaN

In [ ]:
print(str(df["phoneme"].unique()))
v = ["u:","œ̃", "ɨ", "œ", "y̥", "ø̰", "ɪ", "ə̰", "æ", "aː", "ə", "ʉ", "a̰", "ɛ̰", "ɑ̰̃", "ɛ̃", "i̥", "ɑ̃ː", "ɛ", "u", "y", "o", "e", "ɑ", "ø", "a", "ɑ̃", "i"]

<StringArray>
[  'd',   'i',   'ʒ',  'ɑ̃',   'ʃ',   't',   'ʁ',   'w',   'a',   'f',   'j',
   'y',   'k',   's',   'p',   'o',   'z',   'e',   'ɑ',   'ø',   'ɡ', 't͡s',
   'n',   'l',   'u',   'v',   'ɛ',   'ʀ',   'b',  'ʁ̥',   'ŋ', 'ɑ̃ː',  'b̥',
   'ə',  'ʒ̥',   'ʉ',  'ɡ̥',  'sː',  'l̝',  'a̰',  'ɛ̰', 'ɑ̰̃',  'ɛ̃',  'i̥',
   'ʐ',   'ɕ',  'ʀ̥',  'aː',  'tʲ',   'æ',  'l̰',   'ɬ',  'lʲ',  'ə̰',   'ɪ',
  'l̥',  'y̥',   'ɫ',  'ʁ̞',  'ʒʲ',  'd̥',  'pʰ',  'ø̰',   'ʂ',  'ç',  'n̰',
  'v̥',   'h',   'x',  'sʲ',   'ʝ',  'ʒ̞',  'j̥', 'd͡ʒ',  'œ̃',   'ɨ',   'œ',
  'u:',  'ʃː']
Length: 79, dtype: str
2