In [7]:
import pandas as pd

In [9]:
df = pd.read_csv("../outputs/table.csv")
df.sample(5)

,phoneme_id,speaker_id,sentence_id,repetition,phoneme,onset_s,offset_s,duration_ms,l1_status,gender,wav_path,tg_path
8477,KB_distractor_rep2_p9_y,KB,distractor,2,y,1.94000,2.08000,140.00,L2,f,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
16111,SD_tulle_rep5_p7_ɑ,SD,tulle,5,ɑ,1.35000,1.41119,61.19,L1,f,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
4883,AR_cache cache_rep2_p10_w,AR,cache cache,2,w,1.37000,1.40000,30.00,L1,m,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
18558,SV_tsarine_rep5_p2_t͡s,SV,tsarine,5,t͡s,1.01771,1.17019,152.48,L1,m,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...
5571,AR_distractor_rep5_p3_s,AR,distractor,5,s,0.72000,0.80000,80.00,L1,m,/home/onyxia/work/data/ru-fr_interference/2/wa...,/home/onyxia/work/data/ru-fr_interference/2/wa...

In [11]:
df = pd.read_csv("../outputs/features_acoustic.csv")
df.sample(5)

,phoneme_id,F1_mid,F2_mid,F3_mid,f0_mid,SCG,F1_25,F2_25,F1_75,F2_75
12913,RN_pour gabriel_rep5_p8_ʁ,1416.682334,2981.881094,3358.036449,NaN,245.172208,NaN,NaN,NaN,NaN
10501,MD_pour gabriel_rep3_p1_i,268.739616,1670.230443,2772.762852,129.103548,411.007320,282.296102,1646.086048,260.687337,1733.199532
10698,MD_pour gabriel_rep4_p6_b,222.129692,1159.951429,2376.744311,98.907092,240.356072,NaN,NaN,NaN,NaN
8766,KL_j'en chie_rep5_p2_ʐ,1750.957772,2174.441690,2940.224616,109.466717,723.792815,NaN,NaN,NaN,NaN
19163,YC_cache cache_rep6_p9_ʁ,787.904238,1367.843746,2561.274534,NaN,2587.576754,NaN,NaN,NaN,NaN